[tool.poetry]
name = "ml-projects"
version = "0.1.0"
description = ""
authors = ["SL Chang"]
readme = "README.md"
packages = [{include = "ml_projects"}]

[tool.poetry.dependencies]
python = "^3.10"
scikit-learn = "1.2.1"
pydantic = "^1.10.7"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
ipykernel = "^6.22.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
