branch-defaults:
  Fix-deployment:
    environment: imdb-sentiment-predictor-env
    group_suffix: null
global:
  application_name: imdb_sentiment_analysis_app
  branch: null
  default_ec2_keyname: mlflow
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
