name: Run tests

on:
  pull_request:
env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-central-1

jobs:
  run-tests:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: '1.5.1'

    - name: Install dependencies
      run: |
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Pull model by dvc
      run: |
        dvc pull model/model.pkl

    - name: Run black check
      run: |
        black --check .

    - name: Check code with Ruff
      run: |
        ruff check imdb_sentiment tests

    - name: Run tests
      run: |
        pytest -s tests
        